# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
        ('testresults', '0003_auto_20170814_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testsuites', to='repository.Repository')),
                ('test_classes', models.ManyToManyField(to='testresults.TestClass')),
            ],
        ),
    ]
