# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testresults', '0004_testsuite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuite',
            name='test_classes',
        ),
        migrations.AddField(
            model_name='testclass',
            name='test_suites',
            field=models.ManyToManyField(to='testresults.TestSuite'),
        ),
    ]
