# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testresults', '0005_auto_20170817_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='testclass',
            name='kind',
            field=models.CharField(choices=[(b'apex', b'Apex'), (b'browser', b'Browser'), (b'perf', b'Performance'), (b'other', b'Other')], default='other', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsuite',
            name='kind',
            field=models.CharField(choices=[(b'apex', b'Apex'), (b'browser', b'Browser'), (b'perf', b'Performance'), (b'other', b'Other')], default='other', max_length=15),
            preserve_default=False,
        ),
    ]
