# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testresults', '0006_auto_20170817_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsuite',
            options={'verbose_name': 'Test Suite', 'verbose_name_plural': 'Test Suites'},
        ),
    ]
