# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testresults', '0007_auto_20170817_2153'),
        ('plan', '0007_plan_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='test_suites',
            field=models.ManyToManyField(to='testresults.TestSuite'),
        ),
    ]
